### ISSUE TITLE
Provide a way to merge in local (unsourced) configs

### ISSUE THREAD

**Issue by timkelty** [pilwon/node-get-config#2]
I'm migrating from `node-config` and one thing I liked about that was that it automatically merged `local` config files, intended for local, unsourced overrides.

It would be great in `node-get-config` would merge in things from an optional `local` folder as a last step in merging.

Thoughts?

**Comment by pilwon** [comment]
@timkelty What is the example use case for this feature? Can't such values be inserted in the default (all-env) config files that are overridden by environment-specific values?

You often need more than a plain JSON-like object for final config manipulation (ex: JS code to check against other things before deciding what values to override) so I am not sure about the usefulness of this extra magic feature. (`config.js` mentioned in #1 would be a great place for that.)

**Comment by timkelty** [comment]
The use case for me is for settings that are either
- too specific to have in source (user specific)
- or more of a temporary override.

E.g
`config/local/general.yml`

``` yml
devMode: true
testToEmailAddress: somelocaldev@server.com
browserSync:
  open: true
```

**Comment by pilwon** [comment]
@timkelty Thanks for the use case. I've just added this feature in v0.4.6. It reads `_override` directory and the values are used in the final step in the merge step as you expect.

You can also change the directory name by assigning any string you want like this: `require('get-config').OVERRIDE_DIR = 'local';`.

**Comment by timkelty** [comment]
Thanks! love it.

**Comment by pilwon** [comment]
@timkelty Haha that was fast. Have you already tried this? Does it work for you?

Could I ask your help to add some documentation about this feature to the README page?

**Comment by timkelty** [comment]
Not yet. Just loving it from afar. I'll try it out tonight, though!
