### ISSUE TITLE
Cannot use .js (module.exports)

### ISSUE THREAD

**Issue by timkelty** [pilwon/node-get-config#3]
I have a few config files (e.g. [webpack](http://webpack.github.io/docs/configuration.html)) that are `.js` with a `module.exports`. Seemingly this is not supported by node-get-config.

I'm converting from https://www.npmjs.com/package/config, where I could have `.js` config files.

Is this something you would consider adding or accept a PR?

**Comment by pilwon** [comment]
@timkelty Absolutely. I'll be happy to merge your PR.

**Comment by pilwon** [comment]
@timkelty v0.4.7 includes this feature. Thanks for the PR.
