### ISSUE TITLE
Merge in local (unsourced changes)

### ISSUE THREAD

**Issue by timkelty** [pilwon/node-get-config#4]
Other node config libraries have the concept of a "local" config, that would be merged in last, meant for local, unsourced overrides.

So for `node-get-config`, this would mean a `config/local` folder that got merged in last.

Any thoughts about this? Do you think this is something that should/could be built-in, or something that should be done manually?

https://github.com/HenrikJoreteg/getconfig#where-to-put-your-config-and-what-to-call-it
https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order

**Comment by timkelty** [comment]
Ah, just just spotted `_override` in the code. That's what that is for, yes?

**Comment by pilwon** [comment]
@timkelty That's right. Please refer to the issue #2. It turns out you requested this feature :)

**Comment by timkelty** [comment]
Ha! So much for my memory...

**Comment by pilwon** [comment]
Glad to see you came back. I'm always open to great ideas so let me know if you find anything that deserves an improvement :+1:
